name: Telegram Notification

on:
  push:
    tags:
      - "v*"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram notification
        run: |
          TAG="${{ github.ref_name }}"

          MESSAGE="<b>🚀 Deploy Successful!</b>
          <b>🌐 Site:</b> <a href='https://neforceo.ilnazik.dev'>neforceo.ilnazik.dev</a>

          <b>📦 Release:</b> ${TAG}

          <b>👤 Author:</b> ${{ github.actor }}
          <b>🕐 Time:</b> ${{ github.event.head_commit.timestamp }}

          <b>🔗 Release:</b> https://github.com/${{ github.repository }}/releases/tag/${TAG}"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            --data-urlencode "text=${MESSAGE}" \
            -d "parse_mode=HTML"
